casual:
  Type: 1
  FingersInvolved: []
  JointsInvolvedCount:
    base_to_left_finger: 1
    base_to_right_finger: 1
    left_finger_to_left_fingertip: 1
    right_finger_to_right_fingertip: 1
  JointPos:
    base_to_left_finger: [1.381167073873803]
    base_to_right_finger: [-1.250757985142991]
    left_finger_to_left_fingertip: [1.115350311342627]
    right_finger_to_right_fingertip: [-0.6927959559950978]

