grasp:
  Type: 2
  Independent: true
  NInnerActions: 2
  InnerActionsNames: [trig, trig]
  FingersInvolved: [left_fingertip, right_fingertip]
  JointsInvolvedCount:
    base_to_left_finger: 1
    base_to_right_finger: 1
    left_finger_to_left_fingertip: 1
    right_finger_to_right_fingertip: 1
  JointPos:
    base_to_left_finger: [0.7]
    base_to_right_finger: [-0.7]
    left_finger_to_left_fingertip: [0.9]
    right_finger_to_right_fingertip: [-0.9]

