timed_random:
# 0.000000 -----> SPREAD -----> 0.200000 + 0.000000 -----> PINCH -----> 0.200000
  Type: 3
  FingersInvolved: [left_hand_c, left_hand_q, left_hand_r, left_hand_t]
  JointsInvolvedCount:
    left_hand_Finger_Spread: 2
    left_hand_Index_Finger_Distal: 0
    left_hand_Index_Finger_Proximal: 0
    left_hand_Middle_Finger_Distal: 0
    left_hand_Middle_Finger_Proximal: 0
    left_hand_Pinky: 1
    left_hand_Ring_Finger: 0
    left_hand_Thumb_Flexion: 1
    left_hand_Thumb_Opposition: 1
  ActionsNamesOrdered: [SPREAD, PINCH]
  ActionsTimeMargins:
    SPREAD:
      marginBefore: 2
      marginAfter: 5
    PINCH:
      marginBefore: 3
      marginAfter: 0.2
  ActionsJointPos:
    SPREAD:
      left_hand_Finger_Spread: [0.5829]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0]
    PINCH:
      left_hand_Finger_Spread: [0.1833527482867241]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.731481139114243]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0.6771412832986564]
      left_hand_Thumb_Opposition: [0.9756118408639916]
  ActionsJointCount:
    SPREAD:
      left_hand_Finger_Spread: 1
      left_hand_Index_Finger_Distal: 0
      left_hand_Index_Finger_Proximal: 0
      left_hand_Middle_Finger_Distal: 0
      left_hand_Middle_Finger_Proximal: 0
      left_hand_Pinky: 0
      left_hand_Ring_Finger: 0
      left_hand_Thumb_Flexion: 0
      left_hand_Thumb_Opposition: 0
    PINCH:
      left_hand_Finger_Spread: 1
      left_hand_Index_Finger_Distal: 0
      left_hand_Index_Finger_Proximal: 0
      left_hand_Middle_Finger_Distal: 0
      left_hand_Middle_Finger_Proximal: 0
      left_hand_Pinky: 1
      left_hand_Ring_Finger: 0
      left_hand_Thumb_Flexion: 1
      left_hand_Thumb_Opposition: 1

