grasp:
  Type: 2
  Independent: true
  NInnerActions: 5
  InnerActionsNames: [trig, trig, trig, trig, trig]
  FingersInvolved: [left_hand_c, left_hand_q, left_hand_r, left_hand_s, left_hand_t]
  JointsInvolvedCount:
    left_hand_Finger_Spread: 0
    left_hand_Index_Finger_Distal: 1
    left_hand_Index_Finger_Proximal: 1
    left_hand_Middle_Finger_Distal: 1
    left_hand_Middle_Finger_Proximal: 1
    left_hand_Pinky: 1
    left_hand_Ring_Finger: 1
    left_hand_Thumb_Flexion: 1
    left_hand_Thumb_Opposition: 0
  JointPos:
    left_hand_Finger_Spread: [0]
    left_hand_Index_Finger_Distal: [1.334]
    left_hand_Index_Finger_Proximal: [0.79849]
    left_hand_Middle_Finger_Distal: [1.334]
    left_hand_Middle_Finger_Proximal: [0.79849]
    left_hand_Pinky: [0.98175]
    left_hand_Ring_Finger: [0.98175]
    left_hand_Thumb_Flexion: [0.9704]
    left_hand_Thumb_Opposition: [0]

