[index, middle]:
  PrimitiveType: 1
  ActionName: pinchLoose
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 1
    left_hand_Index_Finger_Proximal: 1
    left_hand_Middle_Finger_Distal: 1
    left_hand_Middle_Finger_Proximal: 1
    left_hand_Pinky: 0
    left_hand_Ring_Finger: 0
    left_hand_Thumb_Flexion: 0
    left_hand_Thumb_Opposition: 0
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.03033102788440883]
      left_hand_Index_Finger_Distal: [1.121791189301294]
      left_hand_Index_Finger_Proximal: [0.698633008723734]
      left_hand_Middle_Finger_Distal: [1.30366870360123]
      left_hand_Middle_Finger_Proximal: [0.5637975053120871]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0]
    Optional:
      distance: 0.02562159430767517
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.01407442540694028]
      left_hand_Index_Finger_Distal: [0.07171347765810789]
      left_hand_Index_Finger_Proximal: [0.733016756359553]
      left_hand_Middle_Finger_Distal: [1.126530761844013]
      left_hand_Middle_Finger_Proximal: [0.3361553963681357]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0]
    Optional:
      distance: 0.02568684642796241
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.007914196570543573]
      left_hand_Index_Finger_Distal: [0.3378054561307654]
      left_hand_Index_Finger_Proximal: [0.4974086127379048]
      left_hand_Middle_Finger_Distal: [0.9267713684611955]
      left_hand_Middle_Finger_Proximal: [0.1935206822364358]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0]
    Optional:
      distance: 0.02573818944479525

[index, pinky]:
  PrimitiveType: 1
  ActionName: pinchLoose
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 1
    left_hand_Index_Finger_Proximal: 1
    left_hand_Middle_Finger_Distal: 0
    left_hand_Middle_Finger_Proximal: 0
    left_hand_Pinky: 1
    left_hand_Ring_Finger: 0
    left_hand_Thumb_Flexion: 0
    left_hand_Thumb_Opposition: 1
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.09104936630004085]
      left_hand_Index_Finger_Distal: [1.20718620960135]
      left_hand_Index_Finger_Proximal: [0.766819899183109]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.6975491003071075]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.8970318753007567]
    Optional:
      distance: 0.02867873289742566
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.03808790092205163]
      left_hand_Index_Finger_Distal: [1.315379362863954]
      left_hand_Index_Finger_Proximal: [0.5777086576848873]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.7298313773944974]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9452451999419834]
    Optional:
      distance: 0.02952126780451697
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.001033972179028205]
      left_hand_Index_Finger_Distal: [1.295486267326865]
      left_hand_Index_Finger_Proximal: [0.6211636048655794]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.772068133545632]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9221092089751269]
    Optional:
      distance: 0.02982336754503843

[pinky, ring]:
  PrimitiveType: 1
  ActionName: pinchLoose
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 0
    left_hand_Index_Finger_Proximal: 0
    left_hand_Middle_Finger_Distal: 0
    left_hand_Middle_Finger_Proximal: 0
    left_hand_Pinky: 1
    left_hand_Ring_Finger: 1
    left_hand_Thumb_Flexion: 0
    left_hand_Thumb_Opposition: 1
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.03620832467798609]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.8669649229065981]
      left_hand_Ring_Finger: [0.94453751333541]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9649887130268616]
    Optional:
      distance: 0.02523642232892383
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.0678764326065313]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.8913506976368953]
      left_hand_Ring_Finger: [0.9650045426423313]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.6414155366461957]
    Optional:
      distance: 0.02534289264239489
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.02078398460762109]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.9673849664484733]
      left_hand_Ring_Finger: [0.9735322985983221]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.2053999706732109]
    Optional:
      distance: 0.02534706125535675

