[index]:
  PrimitiveType: 4
  ActionName: tipFlex
  JointsInvolvedCount:
    left_hand_Finger_Spread: 0
    left_hand_Index_Finger_Distal: 1
    left_hand_Index_Finger_Proximal: 0
    left_hand_Middle_Finger_Distal: 0
    left_hand_Middle_Finger_Proximal: 0
    left_hand_Pinky: 0
    left_hand_Ring_Finger: 0
    left_hand_Thumb_Flexion: 0
    left_hand_Thumb_Opposition: 0
  ActionState_1:
    JointPos:
      left_hand_Finger_Spread: [0]
      left_hand_Index_Finger_Distal: [1.334]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0]

[middle]:
  PrimitiveType: 4
  ActionName: tipFlex
  JointsInvolvedCount:
    left_hand_Finger_Spread: 0
    left_hand_Index_Finger_Distal: 0
    left_hand_Index_Finger_Proximal: 0
    left_hand_Middle_Finger_Distal: 1
    left_hand_Middle_Finger_Proximal: 0
    left_hand_Pinky: 0
    left_hand_Ring_Finger: 0
    left_hand_Thumb_Flexion: 0
    left_hand_Thumb_Opposition: 0
  ActionState_1:
    JointPos:
      left_hand_Finger_Spread: [0]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [1.334]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0]

