[left_fingertip]:
  ActionState_1:
    JointStates:
      base_to_left_finger: [0.4]
      base_to_right_finger: [0]
      left_finger_to_left_fingertip: [0]
      right_finger_to_right_fingertip: [0]

[right_fingertip]:
  ActionState_1:
    JointStates:
      base_to_left_finger: [0]
      base_to_right_finger: [-0.3]
      left_finger_to_left_fingertip: [0]
      right_finger_to_right_fingertip: [0]

