[left_fingertip, right_fingertip]:
  PrimitiveType: 0
  ActionName: pinchStrong
  JointsInvolvedCount:
    base_to_left_finger: 1
    base_to_right_finger: 1
    left_finger_to_left_fingertip: 1
    right_finger_to_right_fingertip: 1
  ActionState_1:
    JointPos:
      base_to_left_finger: [0.6905835369369014]
      base_to_right_finger: [-0.6253789925714954]
      left_finger_to_left_fingertip: [0.5576751556713134]
      right_finger_to_right_fingertip: [-0.3463979779975489]
    Optional:
      MoveItContact:
        body_name_1: right_fingertip
        body_name_2: left_fingertip
        body_type_1: 0
        body_type_2: 0
        depth: -0.1
        normal: [0, -0, 1]
        pos: [0.1138615803508818, -1.089958602276067, -0.05]
  ActionState_2:
    JointPos:
      base_to_left_finger: [0.6807236284017563]
      base_to_right_finger: [-0.6198662493145093]
      left_finger_to_left_fingertip: [0.4261813441989943]
      right_finger_to_right_fingertip: [-0.699923454131931]
    Optional:
      MoveItContact:
        body_name_1: left_fingertip
        body_name_2: right_fingertip
        body_type_1: 0
        body_type_2: 0
        depth: -0.0945950817375851
        normal: [0.4474315945415338, 0.8943181582669674, 0]
        pos: [-0.07713564845128959, -1.05331867059697, -0.05]
  ActionState_3:
    JointPos:
      base_to_left_finger: [0.6167701796861365]
      base_to_right_finger: [-0.644209223310463]
      left_finger_to_left_fingertip: [0.790307210222818]
      right_finger_to_right_fingertip: [-0.6129278627922758]
    Optional:
      MoveItContact:
        body_name_1: left_fingertip
        body_name_2: right_fingertip
        body_type_1: 0
        body_type_2: 0
        depth: -0.09437064064693647
        normal: [0.3085414040461401, -0.9512109135145773, -0]
        pos: [0.05713572698126742, -0.9296779235723844, -0.05]

