[left_fingertip]:
  PrimitiveType: 4
  ActionName: tipFlex
  JointsInvolvedCount:
    base_to_left_finger: 0
    base_to_right_finger: 0
    left_finger_to_left_fingertip: 1
    right_finger_to_right_fingertip: 0
  ActionState_1:
    JointPos:
      base_to_left_finger: [0]
      base_to_right_finger: [0]
      left_finger_to_left_fingertip: [0.9]
      right_finger_to_right_fingertip: [0]

[right_fingertip]:
  PrimitiveType: 4
  ActionName: tipFlex
  JointsInvolvedCount:
    base_to_left_finger: 0
    base_to_right_finger: 0
    left_finger_to_left_fingertip: 0
    right_finger_to_right_fingertip: 1
  ActionState_1:
    JointPos:
      base_to_left_finger: [0]
      base_to_right_finger: [0]
      left_finger_to_left_fingertip: [0]
      right_finger_to_right_fingertip: [-0.9]

