[left_hand_s]:
  PrimitiveType: 5
  ActionName: fingFlex
  JointsInvolvedCount:
    left_hand_Finger_Spread: 0
    left_hand_Index_Finger_Distal: 0
    left_hand_Index_Finger_Proximal: 0
    left_hand_Middle_Finger_Distal: 0
    left_hand_Middle_Finger_Proximal: 1
    left_hand_Pinky: 0
    left_hand_Ring_Finger: 0
    left_hand_Thumb_Flexion: 0
    left_hand_Thumb_Opposition: 0
  ActionState_1:
    JointPos:
      left_hand_Finger_Spread: [0]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0.79849]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0]

[left_hand_t]:
  PrimitiveType: 5
  ActionName: fingFlex
  JointsInvolvedCount:
    left_hand_Finger_Spread: 0
    left_hand_Index_Finger_Distal: 0
    left_hand_Index_Finger_Proximal: 1
    left_hand_Middle_Finger_Distal: 0
    left_hand_Middle_Finger_Proximal: 0
    left_hand_Pinky: 0
    left_hand_Ring_Finger: 0
    left_hand_Thumb_Flexion: 0
    left_hand_Thumb_Opposition: 0
  ActionState_1:
    JointPos:
      left_hand_Finger_Spread: [0]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0.79849]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0]

