left_hand_Finger_Spread:
  PrimitiveType: 6
  ActionName: moreTips_3
  FingersInvolved: [left_hand_q, left_hand_r, left_hand_t]
  JointPosFurther:
    left_hand_Finger_Spread: [0.5829]
    left_hand_Index_Finger_Distal: [0]
    left_hand_Index_Finger_Proximal: [0]
    left_hand_Middle_Finger_Distal: [0]
    left_hand_Middle_Finger_Proximal: [0]
    left_hand_Pinky: [0]
    left_hand_Ring_Finger: [0]
    left_hand_Thumb_Flexion: [0]
    left_hand_Thumb_Opposition: [0]
  JointPosNearer:
    left_hand_Finger_Spread: [0]
    left_hand_Index_Finger_Distal: [0]
    left_hand_Index_Finger_Proximal: [0]
    left_hand_Middle_Finger_Distal: [0]
    left_hand_Middle_Finger_Proximal: [0]
    left_hand_Pinky: [0]
    left_hand_Ring_Finger: [0]
    left_hand_Thumb_Flexion: [0]
    left_hand_Thumb_Opposition: [0]

left_hand_Thumb_Opposition:
  PrimitiveType: 6
  ActionName: moreTips_3
  FingersInvolved: [left_hand_c, left_hand_q, left_hand_r]
  JointPosFurther:
    left_hand_Finger_Spread: [0]
    left_hand_Index_Finger_Distal: [0]
    left_hand_Index_Finger_Proximal: [0]
    left_hand_Middle_Finger_Distal: [0]
    left_hand_Middle_Finger_Proximal: [0]
    left_hand_Pinky: [0]
    left_hand_Ring_Finger: [0]
    left_hand_Thumb_Flexion: [0]
    left_hand_Thumb_Opposition: [0.9879]
  JointPosNearer:
    left_hand_Finger_Spread: [0]
    left_hand_Index_Finger_Distal: [0]
    left_hand_Index_Finger_Proximal: [0]
    left_hand_Middle_Finger_Distal: [0]
    left_hand_Middle_Finger_Proximal: [0]
    left_hand_Pinky: [0]
    left_hand_Ring_Finger: [0]
    left_hand_Thumb_Flexion: [0]
    left_hand_Thumb_Opposition: [0]

