[left_hand_c, left_hand_q, left_hand_s]:
  PrimitiveType: 2
  ActionName: multiplePinchStrong_3
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 0
    left_hand_Index_Finger_Proximal: 0
    left_hand_Middle_Finger_Distal: 1
    left_hand_Middle_Finger_Proximal: 1
    left_hand_Pinky: 1
    left_hand_Ring_Finger: 0
    left_hand_Thumb_Flexion: 1
    left_hand_Thumb_Opposition: 1
  ActionState_1:
    JointPos:
      left_hand_Finger_Spread: [0.3725872360624373]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [1.281230863642879]
      left_hand_Middle_Finger_Proximal: [0.6662191092730151]
      left_hand_Pinky: [0.6572310223917012]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0.6339003265628591]
      left_hand_Thumb_Opposition: [0.9294838788260473]
    Optional:
      DepthSum: 0.00139970998668696
  ActionState_2:
    JointPos:
      left_hand_Finger_Spread: [0.01468652392546646]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [1.265196226162836]
      left_hand_Middle_Finger_Proximal: [0.7667579998413451]
      left_hand_Pinky: [0.7479649838201003]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0.623680734760873]
      left_hand_Thumb_Opposition: [0.9279877990346169]
    Optional:
      DepthSum: 0.001543863732090868

[left_hand_c, left_hand_r, left_hand_s]:
  PrimitiveType: 2
  ActionName: multiplePinchStrong_3
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 0
    left_hand_Index_Finger_Proximal: 0
    left_hand_Middle_Finger_Distal: 1
    left_hand_Middle_Finger_Proximal: 1
    left_hand_Pinky: 0
    left_hand_Ring_Finger: 1
    left_hand_Thumb_Flexion: 1
    left_hand_Thumb_Opposition: 1
  ActionState_1:
    JointPos:
      left_hand_Finger_Spread: [0.1786526794612873]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [1.315071946357377]
      left_hand_Middle_Finger_Proximal: [0.6399074626221415]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.9463292705590138]
      left_hand_Thumb_Flexion: [0.7979311068082229]
      left_hand_Thumb_Opposition: [0.408167340079369]
    Optional:
      DepthSum: 0.0005185396161881649
  ActionState_2:
    JointPos:
      left_hand_Finger_Spread: [0.2517861274231458]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [1.332891534464899]
      left_hand_Middle_Finger_Proximal: [0.5918846452726005]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.9219594126432202]
      left_hand_Thumb_Flexion: [0.8747908815335482]
      left_hand_Thumb_Opposition: [0.3565782549295575]
    Optional:
      DepthSum: 0.001332521797632918
  ActionState_3:
    JointPos:
      left_hand_Finger_Spread: [0.05261202563520055]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [1.327512155741919]
      left_hand_Middle_Finger_Proximal: [0.7680602073273645]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.8756380825163796]
      left_hand_Thumb_Flexion: [0.6938878928141669]
      left_hand_Thumb_Opposition: [0.3252411207991652]
    Optional:
      DepthSum: 0.00227081686815903

[left_hand_c, left_hand_r, left_hand_t]:
  PrimitiveType: 2
  ActionName: multiplePinchStrong_3
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 1
    left_hand_Index_Finger_Proximal: 1
    left_hand_Middle_Finger_Distal: 0
    left_hand_Middle_Finger_Proximal: 0
    left_hand_Pinky: 0
    left_hand_Ring_Finger: 1
    left_hand_Thumb_Flexion: 1
    left_hand_Thumb_Opposition: 1
  ActionState_1:
    JointPos:
      left_hand_Finger_Spread: [0.1284305579523789]
      left_hand_Index_Finger_Distal: [1.181699874100741]
      left_hand_Index_Finger_Proximal: [0.7903563095901628]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.8256708457118366]
      left_hand_Thumb_Flexion: [0.7184572644738481]
      left_hand_Thumb_Opposition: [0.6953091374797979]
    Optional:
      DepthSum: 0.001791446051603501
  ActionState_2:
    JointPos:
      left_hand_Finger_Spread: [0.5154608870037133]
      left_hand_Index_Finger_Distal: [1.056746659815777]
      left_hand_Index_Finger_Proximal: [0.7560109353148589]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.7795847885637777]
      left_hand_Thumb_Flexion: [0.5776794972481206]
      left_hand_Thumb_Opposition: [0.7343506129867164]
    Optional:
      DepthSum: 0.002158738824884666
  ActionState_3:
    JointPos:
      left_hand_Finger_Spread: [0.4497272428708384]
      left_hand_Index_Finger_Distal: [0.9568435972919688]
      left_hand_Index_Finger_Proximal: [0.7018960855434719]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.7607045136333327]
      left_hand_Thumb_Flexion: [0.6106608642261475]
      left_hand_Thumb_Opposition: [0.8853184448791668]
    Optional:
      DepthSum: 0.002906010601602535

