[left_hand_c, left_hand_q]:
  PrimitiveType: 0
  ActionName: pinchStrong
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 0
    left_hand_Index_Finger_Proximal: 0
    left_hand_Middle_Finger_Distal: 0
    left_hand_Middle_Finger_Proximal: 0
    left_hand_Pinky: 1
    left_hand_Ring_Finger: 0
    left_hand_Thumb_Flexion: 1
    left_hand_Thumb_Opposition: 1
  ActionState_1:
    JointPos:
      left_hand_Finger_Spread: [0.1833527482867241]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.731481139114243]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0.6771412832986564]
      left_hand_Thumb_Opposition: [0.9756118408639916]
    Optional:
      MoveItContact:
        body_name_1: left_hand_q
        body_name_2: left_hand_c
        body_type_1: 0
        body_type_2: 0
        depth: 0.002725382975380944
        normal: [0.2678359422698244, -0.3300608796594851, 0.9051650256979898]
        pos: [0.007591852781181429, 0.04532851096438649, 0.1234466028664572]
  ActionState_2:
    JointPos:
      left_hand_Finger_Spread: [0.01385087144386489]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.7234533601248404]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0.7149321797635406]
      left_hand_Thumb_Opposition: [0.8397594591506989]
    Optional:
      MoveItContact:
        body_name_1: left_hand_c
        body_name_2: left_hand_q
        body_type_1: 0
        body_type_2: 0
        depth: 0.002038639814590014
        normal: [-0.1234779694919966, 0.4445058885784077, -0.8872247212906399]
        pos: [0.007093052788931763, 0.04456237185565301, 0.1222378974460804]
  ActionState_3:
    JointPos:
      left_hand_Finger_Spread: [0.04735388111458159]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.7171745373904123]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0.6482287617508322]
      left_hand_Thumb_Opposition: [0.9031521967854118]
    Optional:
      MoveItContact:
        body_name_1: left_hand_c
        body_name_2: left_hand_q
        body_type_1: 0
        body_type_2: 0
        depth: 0.001797388015650485
        normal: [-0.8395190412178047, 0.523503599613278, -0.1454364487488545]
        pos: [0.01293511489020363, 0.0465715166528359, 0.1123247679576194]

[left_hand_c, left_hand_r]:
  PrimitiveType: 0
  ActionName: pinchStrong
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 0
    left_hand_Index_Finger_Proximal: 0
    left_hand_Middle_Finger_Distal: 0
    left_hand_Middle_Finger_Proximal: 0
    left_hand_Pinky: 0
    left_hand_Ring_Finger: 1
    left_hand_Thumb_Flexion: 1
    left_hand_Thumb_Opposition: 1
  ActionState_1:
    JointPos:
      left_hand_Finger_Spread: [0.4405453122053761]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.6563804978894187]
      left_hand_Thumb_Flexion: [0.5217104099111631]
      left_hand_Thumb_Opposition: [0.663058916883613]
    Optional:
      MoveItContact:
        body_name_1: left_hand_r
        body_name_2: left_hand_c
        body_type_1: 0
        body_type_2: 0
        depth: 0.003678275356822872
        normal: [0.9596930330967737, -0.1609127897163021, 0.2304264662126128]
        pos: [0.01625199202692948, 0.04624098750543007, 0.133995245240407]
  ActionState_2:
    JointPos:
      left_hand_Finger_Spread: [0.02840000214669853]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.6410372098736116]
      left_hand_Thumb_Flexion: [0.5095780665185303]
      left_hand_Thumb_Opposition: [0.6582619406526675]
    Optional:
      MoveItContact:
        body_name_1: left_hand_c
        body_name_2: left_hand_r
        body_type_1: 0
        body_type_2: 0
        depth: 0.002904631860886429
        normal: [0.112769769173005, -0.9228566630929216, 0.3682642509743035]
        pos: [0.02519925822304271, 0.04717580302357322, 0.130635573726946]
  ActionState_3:
    JointPos:
      left_hand_Finger_Spread: [0.1614500040797749]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.8176685153848375]
      left_hand_Thumb_Flexion: [0.7464561491593719]
      left_hand_Thumb_Opposition: [0.7490800512397662]
    Optional:
      MoveItContact:
        body_name_1: left_hand_c
        body_name_2: left_hand_r
        body_type_1: 0
        body_type_2: 0
        depth: 0.002689503886221023
        normal: [0.553158984804799, -0.233597941969255, -0.7996543872432968]
        pos: [0.02124641695464478, 0.03936332169361635, 0.1192194442891853]

[left_hand_c, left_hand_s]:
  PrimitiveType: 0
  ActionName: pinchStrong
  JointsInvolvedCount:
    left_hand_Finger_Spread: 0
    left_hand_Index_Finger_Distal: 0
    left_hand_Index_Finger_Proximal: 0
    left_hand_Middle_Finger_Distal: 1
    left_hand_Middle_Finger_Proximal: 1
    left_hand_Pinky: 0
    left_hand_Ring_Finger: 0
    left_hand_Thumb_Flexion: 1
    left_hand_Thumb_Opposition: 1
  ActionState_1:
    JointPos:
      left_hand_Finger_Spread: [0]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [1.185076125533786]
      left_hand_Middle_Finger_Proximal: [0.6118052107282472]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0.6575574798043817]
      left_hand_Thumb_Opposition: [0.06331152036571876]
    Optional:
      MoveItContact:
        body_name_1: left_hand_s
        body_name_2: left_hand_c
        body_type_1: 0
        body_type_2: 0
        depth: 0.002986960034628994
        normal: [-0.4847268248858084, -0.2593324144042312, -0.8353362221736795]
        pos: [-0.003004028585318193, 0.04347870537112229, 0.1271892799357285]
  ActionState_2:
    JointPos:
      left_hand_Finger_Spread: [0]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [1.241007477528416]
      left_hand_Middle_Finger_Proximal: [0.6937400759132836]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0.8370644840599969]
      left_hand_Thumb_Opposition: [0.0767433311625151]
    Optional:
      MoveItContact:
        body_name_1: left_hand_c
        body_name_2: left_hand_s
        body_type_1: 0
        body_type_2: 0
        depth: 0.002517696562327926
        normal: [0.9850563836964086, -0.0363603110328662, -0.1683503748749814]
        pos: [-0.004765508154820762, 0.04318192561988825, 0.1181830893656478]
  ActionState_3:
    JointPos:
      left_hand_Finger_Spread: [0]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [1.149551583808847]
      left_hand_Middle_Finger_Proximal: [0.7784789317530184]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0.7256870338212699]
      left_hand_Thumb_Opposition: [0.2742369753483217]
    Optional:
      MoveItContact:
        body_name_1: left_hand_c
        body_name_2: left_hand_s
        body_type_1: 0
        body_type_2: 0
        depth: 0.001877325660634903
        normal: [0.2752064324980985, 0.420568148638341, -0.864513650477879]
        pos: [0.007578451286430033, 0.04966768523485653, 0.1207754107609236]

[left_hand_c, left_hand_t]:
  PrimitiveType: 0
  ActionName: pinchStrong
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 1
    left_hand_Index_Finger_Proximal: 1
    left_hand_Middle_Finger_Distal: 0
    left_hand_Middle_Finger_Proximal: 0
    left_hand_Pinky: 0
    left_hand_Ring_Finger: 0
    left_hand_Thumb_Flexion: 1
    left_hand_Thumb_Opposition: 1
  ActionState_1:
    JointPos:
      left_hand_Finger_Spread: [0.03683556799027137]
      left_hand_Index_Finger_Distal: [1.233175009112805]
      left_hand_Index_Finger_Proximal: [0.6461676529269805]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0.4649411926487461]
      left_hand_Thumb_Opposition: [0.2914911882700632]
    Optional:
      MoveItContact:
        body_name_1: left_hand_c
        body_name_2: left_hand_t
        body_type_1: 0
        body_type_2: 0
        depth: 0.003300058022772528
        normal: [-0.2927430556525868, -0.95503074334078, 0.0470933396686169]
        pos: [0.03080213666952214, 0.0446258349797979, 0.123098246356448]
  ActionState_2:
    JointPos:
      left_hand_Finger_Spread: [0.1144423930378631]
      left_hand_Index_Finger_Distal: [0.9468243939569221]
      left_hand_Index_Finger_Proximal: [0.6120280037766742]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0.4595575204439462]
      left_hand_Thumb_Opposition: [0.6505139544648584]
    Optional:
      MoveItContact:
        body_name_1: left_hand_c
        body_name_2: left_hand_t
        body_type_1: 0
        body_type_2: 0
        depth: 0.003127514794192491
        normal: [-0.5445022564309488, -0.2339958816528686, 0.8054583912972175]
        pos: [0.0264915089630606, 0.0490324104370342, 0.1322605890168757]
  ActionState_3:
    JointPos:
      left_hand_Finger_Spread: [0.1133315185952]
      left_hand_Index_Finger_Distal: [0.7731635513841175]
      left_hand_Index_Finger_Proximal: [0.7770994166466269]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0.4209920893110335]
      left_hand_Thumb_Opposition: [0.2238125110302586]
    Optional:
      MoveItContact:
        body_name_1: left_hand_t
        body_name_2: left_hand_c
        body_type_1: 0
        body_type_2: 0
        depth: 0.002750051633868319
        normal: [0.4312748486249686, 0.3769065819403595, -0.8197215584779662]
        pos: [0.03436760158486487, 0.05301651219612316, 0.1344714425691103]

[left_hand_q, left_hand_s]:
  PrimitiveType: 0
  ActionName: pinchStrong
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 0
    left_hand_Index_Finger_Proximal: 0
    left_hand_Middle_Finger_Distal: 1
    left_hand_Middle_Finger_Proximal: 1
    left_hand_Pinky: 1
    left_hand_Ring_Finger: 0
    left_hand_Thumb_Flexion: 0
    left_hand_Thumb_Opposition: 1
  ActionState_1:
    JointPos:
      left_hand_Finger_Spread: [0.03840184348099865]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [1.269272651851177]
      left_hand_Middle_Finger_Proximal: [0.6355055903997412]
      left_hand_Pinky: [0.7305116468640045]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.758210423209006]
    Optional:
      MoveItContact:
        body_name_1: left_hand_q
        body_name_2: left_hand_s
        body_type_1: 0
        body_type_2: 0
        depth: 0.002496523829029317
        normal: [0.1669695066370881, -0.3515102760190136, 0.9211740930499535]
        pos: [-0.007973580449252365, 0.04346553552161877, 0.1285265671452913]
  ActionState_2:
    JointPos:
      left_hand_Finger_Spread: [0.2073944040760165]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [1.304493245495949]
      left_hand_Middle_Finger_Proximal: [0.7718063763206033]
      left_hand_Pinky: [0.6850848911773064]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.8559289160309359]
    Optional:
      MoveItContact:
        body_name_1: left_hand_q
        body_name_2: left_hand_s
        body_type_1: 0
        body_type_2: 0
        depth: 0.002359286328276255
        normal: [0.4963079337193849, -0.09689371950429912, -0.8627224594548455]
        pos: [0.00340680958106903, 0.05115188065480426, 0.1241659983526827]
  ActionState_3:
    JointPos:
      left_hand_Finger_Spread: [0.1843567481845384]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [1.220827258590143]
      left_hand_Middle_Finger_Proximal: [0.7226510485412716]
      left_hand_Pinky: [0.7658869989944506]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.7670954553029733]
    Optional:
      MoveItContact:
        body_name_1: left_hand_q
        body_name_2: left_hand_s
        body_type_1: 0
        body_type_2: 0
        depth: 0.002335065990108927
        normal: [0.8793500298061925, 0.4734976579820293, 0.05043305429360906]
        pos: [-0.00528383367847555, 0.04625726030980196, 0.1268646306385196]

[left_hand_r, left_hand_s]:
  PrimitiveType: 0
  ActionName: pinchStrong
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 0
    left_hand_Index_Finger_Proximal: 0
    left_hand_Middle_Finger_Distal: 1
    left_hand_Middle_Finger_Proximal: 1
    left_hand_Pinky: 0
    left_hand_Ring_Finger: 1
    left_hand_Thumb_Flexion: 0
    left_hand_Thumb_Opposition: 1
  ActionState_1:
    JointPos:
      left_hand_Finger_Spread: [0.1234208988758968]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0.9651371455863119]
      left_hand_Middle_Finger_Proximal: [0.2636617145838588]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.3198647598297685]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.6147385727610206]
    Optional:
      MoveItContact:
        body_name_1: left_hand_r
        body_name_2: left_hand_s
        body_type_1: 0
        body_type_2: 0
        depth: 0.002818389196976892
        normal: [-0.8095524329892838, -0.3333957282916989, -0.4831895555555588]
        pos: [-0.002003234196284383, 0.03001271494629883, 0.1762607370531246]
  ActionState_2:
    JointPos:
      left_hand_Finger_Spread: [0.1907810034167021]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0.2344554464686662]
      left_hand_Middle_Finger_Proximal: [0.5195495230580168]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.3224321040875511]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.6809811774834059]
    Optional:
      MoveItContact:
        body_name_1: left_hand_r
        body_name_2: left_hand_s
        body_type_1: 0
        body_type_2: 0
        depth: 0.00271231005614931
        normal: [-0.8202761469926743, -0.2924467264250938, -0.4915505618734441]
        pos: [-0.002003234170259643, 0.02678253825477028, 0.1790656299555174]
  ActionState_3:
    JointPos:
      left_hand_Finger_Spread: [0.102277197221294]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [1.301055416526739]
      left_hand_Middle_Finger_Proximal: [0.5268123061565031]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.5202035108014242]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.4375672878442565]
    Optional:
      MoveItContact:
        body_name_1: left_hand_r
        body_name_2: left_hand_s
        body_type_1: 0
        body_type_2: 0
        depth: 0.002677684347452877
        normal: [0.08255869365501625, -0.9755919247698714, 0.2034808551824828]
        pos: [-0.002003960392206064, 0.04641391567549485, 0.1514751146857957]

[left_hand_r, left_hand_t]:
  PrimitiveType: 0
  ActionName: pinchStrong
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 1
    left_hand_Index_Finger_Proximal: 1
    left_hand_Middle_Finger_Distal: 0
    left_hand_Middle_Finger_Proximal: 0
    left_hand_Pinky: 0
    left_hand_Ring_Finger: 1
    left_hand_Thumb_Flexion: 0
    left_hand_Thumb_Opposition: 1
  ActionState_1:
    JointPos:
      left_hand_Finger_Spread: [0.1132423883671872]
      left_hand_Index_Finger_Distal: [1.205671886306722]
      left_hand_Index_Finger_Proximal: [0.7110034553805133]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.593958172127721]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.7240429239064687]
    Optional:
      MoveItContact:
        body_name_1: left_hand_t
        body_name_2: left_hand_r
        body_type_1: 0
        body_type_2: 0
        depth: 0.002282142928677566
        normal: [0.9384518624013393, 0.1798353377660663, -0.2949022774514012]
        pos: [0.02341439255637146, 0.03665249069461057, 0.1452719935601704]
  ActionState_2:
    JointPos:
      left_hand_Finger_Spread: [0.07848668475751765]
      left_hand_Index_Finger_Distal: [1.309634229615331]
      left_hand_Index_Finger_Proximal: [0.7752564858346339]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.7769543951323139]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.8411868479724973]
    Optional:
      MoveItContact:
        body_name_1: left_hand_r
        body_name_2: left_hand_t
        body_type_1: 0
        body_type_2: 0
        depth: 0.002117888612648776
        normal: [0.4619900261837923, -0.1073212949650788, -0.8803677387056604]
        pos: [0.02645783624101398, 0.04486201743897648, 0.1240400796062639]
  ActionState_3:
    JointPos:
      left_hand_Finger_Spread: [0.174825541315251]
      left_hand_Index_Finger_Distal: [1.261231459143572]
      left_hand_Index_Finger_Proximal: [0.7973591544205929]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0.7978436434707837]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.976319431524491]
    Optional:
      MoveItContact:
        body_name_1: left_hand_r
        body_name_2: left_hand_t
        body_type_1: 0
        body_type_2: 0
        depth: 0.002083041524702912
        normal: [0.9573951254155656, -0.2887508771615774, -0.004183870090458952]
        pos: [0.03094456217032624, 0.03648901819750976, 0.133036838534987]

