[left_hand_q, left_hand_r]:
  PrimitiveType: 1
  ActionName: pinchWeak
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 0
    left_hand_Index_Finger_Proximal: 0
    left_hand_Middle_Finger_Distal: 0
    left_hand_Middle_Finger_Proximal: 0
    left_hand_Pinky: 1
    left_hand_Ring_Finger: 1
    left_hand_Thumb_Flexion: 0
    left_hand_Thumb_Opposition: 1
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.01602783603225835]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.9445623992301989]
      left_hand_Ring_Finger: [0.9807002756487345]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.1685376873629401]
    Optional:
      distance: 0.02477561394183947
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.02398834710870869]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.8611324905527872]
      left_hand_Ring_Finger: [0.9674420263300999]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.1380463998832041]
    Optional:
      distance: 0.02502294248917403
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.0001004472600063309]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.8649528947356158]
      left_hand_Ring_Finger: [0.924879528763122]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.6332979368770961]
    Optional:
      distance: 0.02505712465389534

[left_hand_q, left_hand_t]:
  PrimitiveType: 1
  ActionName: pinchWeak
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 1
    left_hand_Index_Finger_Proximal: 1
    left_hand_Middle_Finger_Distal: 0
    left_hand_Middle_Finger_Proximal: 0
    left_hand_Pinky: 1
    left_hand_Ring_Finger: 0
    left_hand_Thumb_Flexion: 0
    left_hand_Thumb_Opposition: 1
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.03063630043538287]
      left_hand_Index_Finger_Distal: [1.160002055079211]
      left_hand_Index_Finger_Proximal: [0.7976420832406288]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.7557327006259001]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.8388897757521132]
    Optional:
      distance: 0.02982947480485994
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.02940546982367523]
      left_hand_Index_Finger_Distal: [0.7634552146568895]
      left_hand_Index_Finger_Proximal: [0.7673793989724363]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.6898593457881943]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.935468600285193]
    Optional:
      distance: 0.03107588933089525
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.05138095426156651]
      left_hand_Index_Finger_Distal: [1.073023077707272]
      left_hand_Index_Finger_Proximal: [0.7238818054082012]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.4829046345077804]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9851083124999189]
    Optional:
      distance: 0.03197576501948342

[left_hand_s, left_hand_t]:
  PrimitiveType: 1
  ActionName: pinchWeak
  JointsInvolvedCount:
    left_hand_Finger_Spread: 1
    left_hand_Index_Finger_Distal: 1
    left_hand_Index_Finger_Proximal: 1
    left_hand_Middle_Finger_Distal: 1
    left_hand_Middle_Finger_Proximal: 1
    left_hand_Pinky: 0
    left_hand_Ring_Finger: 0
    left_hand_Thumb_Flexion: 0
    left_hand_Thumb_Opposition: 0
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.005807000418333336]
      left_hand_Index_Finger_Distal: [0.7664811693099328]
      left_hand_Index_Finger_Proximal: [0.7038691254819371]
      left_hand_Middle_Finger_Distal: [1.232729032278992]
      left_hand_Middle_Finger_Proximal: [0.540059312993507]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0]
    Optional:
      distance: 0.02526232332847471
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.005946889611985534]
      left_hand_Index_Finger_Distal: [0.8734539641789161]
      left_hand_Index_Finger_Proximal: [0.2727477055482031]
      left_hand_Middle_Finger_Distal: [1.146713212725706]
      left_hand_Middle_Finger_Proximal: [0.07716102021011059]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0]
    Optional:
      distance: 0.02559498835501488
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.002474112035077997]
      left_hand_Index_Finger_Distal: [0.7635157631882467]
      left_hand_Index_Finger_Proximal: [0.5286509457259998]
      left_hand_Middle_Finger_Distal: [1.047815971187316]
      left_hand_Middle_Finger_Proximal: [0.4613938993970305]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0]
    Optional:
      distance: 0.0256194213820208

