#WARNING: DO NOT USE TAB FOR IDENT YAML FILE: This is not permitted by the YAML spec
## urdf and srdf filename
ros_end_effector:
  urdf_path: "urdf/heri_II.urdf"
  srdf_path: "srdf/heri_II.srdf"
  
  
## Arguments for rosee_plugin control for gazebo. Similar syntax to
# the one used by "official" ros plugin http://gazebosim.org/tutorials/?tut=ros_control
rosee_gazebo_plugins_args: #robot name
  #Controller for each joint. type now is only JointPositionControllerfor JointVelocityController
  SFB1__SFP1_1_position_controller:
    type: JointPositionController
    joint_name: SFB1__SFP1_1
    pid: {p: 0.3, i: 0.001, d: 0.00005}

  LFB1__LFP1_1_position_controller:
    type: JointPositionController
    joint_name: LFB1__LFP1_1
    pid: {p: 0.3, i: 0.001, d: 0.00005}

  LFB2__LFP2_1_position_controller:
    type: JointPositionController
    joint_name: LFB2__LFP2_1
    pid: {p: 0.3, i: 0.001, d: 0.00005}
    
  LFB3__LFP3_1_position_controller:
    type: JointPositionController
    joint_name: LFB3__LFP3_1
    pid: {p: 0.3, i: 0.001, d: 0.00005}

    
    
XBotInterface:
  urdf_path: "/home/tori/ROSEE/src/ROSEndEffector/configs/urdf/heri_II.urdf"
  srdf_path: "/home/tori/ROSEE/src/ROSEndEffector/configs/srdf/heri_II.srdf"

ModelInterface:
  model_type: "RBDL"
  is_model_floating_base: "false"
  
RobotInterface:
  framework_name: "ROS" 

xbotcore_threads:
    rt_slow:  {sched: fifo , prio: 60, period: 0.5, core_id: 0}
    rt_main:  {sched: fifo , prio: 60, period: 0.001, core_id: 2}
    nrt_main: {sched: other, prio: 0 , period: 0.005}
  
xbotcore_devices:

    joint_gz:
        names: [__joint_srdf__]  # take all joint ids from srdf/urdf
        thread: rt_main  # allocate this device on rt_main thread

    joint_master:
       master: true  # this is a master device for all 'joint' devices
       thread: rt_main
 
xbotcore_plugins:

    # this plugin is shipped with xbot2, and it generates the
    # ROS api for the framework
    # it is not designed to be real-time safe, so it must executed
    # inside a thread with `other` priority
    ros_io: {thread: nrt_main, type: ros_io}
    ros_ctrl: {thread: nrt_main, type: ros_control} 

# additional parameters that don't relate to any plugin 
xbotcore_param:
    /jm/tx_filter_autostart: {value: true, type: bool}  # autostart joint filter
    /jm/tx_filter_cutoff: {value: 2.0, type: double}    # set default filter bandwidth
    /xbot_internal/ros_io/call_timeout: {value: 1.0, type: chrono}
    /rt_slow/memory_hooks: {value: false, type: bool}
    /jm/enable_safety: {value: false, type: bool}
