ROSEndEffector:
  urdf_path: "/home/lucamuratore/src/ros_end_effector__ws/src/ROSEndEffector/configs/urdf/test_ee.urdf"
  srdf_path: "/home/lucamuratore/src/ros_end_effector__ws/src/ROSEndEffector/configs/srdf/test_ee.srdf"
