ROSEndEffector:
  urdf_path: "/home/lucamuratore/src/ros_end_effector__ws/src/ROSEndEffector/configs/urdf/two_finger.urdf"
  srdf_path: "/home/lucamuratore/src/ros_end_effector__ws/src/ROSEndEffector/configs/srdf/two_finger.srdf"
