[left_fingertip]:
  ActionState_1:
    JointStates:
      base_to_left_finger: [0.7]
      base_to_right_finger1: [0]
      base_to_right_finger2: [0]
      left_finger_to_left_fingertip: [0]
      right_finger1_to_right_fingertip1: [0]
      right_finger2_to_right_fingertip2: [0]

[right_fingertip1]:
  ActionState_1:
    JointStates:
      base_to_left_finger: [0]
      base_to_right_finger1: [-0.7]
      base_to_right_finger2: [0]
      left_finger_to_left_fingertip: [0]
      right_finger1_to_right_fingertip1: [0]
      right_finger2_to_right_fingertip2: [0]

[right_fingertip2]:
  ActionState_1:
    JointStates:
      base_to_left_finger: [0]
      base_to_right_finger1: [0]
      base_to_right_finger2: [-0.7]
      left_finger_to_left_fingertip: [0]
      right_finger1_to_right_fingertip1: [0]
      right_finger2_to_right_fingertip2: [0]

