[left_hand_s]:
  JointsInvolved: [false, false, false, false, true, false, false, false, false]
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0.79849]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0]

[left_hand_t]:
  JointsInvolved: [false, false, true, false, false, false, false, false, false]
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0.79849]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0]

