Name: grasp
Independent: true
nPrimitives: 5
Primitives: [trig, trig, trig, trig, trig]
JointStates:
  left_hand_Finger_Spread: [0]
  left_hand_Index_Finger_Distal: [1.334]
  left_hand_Index_Finger_Proximal: [0.79849]
  left_hand_Middle_Finger_Distal: [1.334]
  left_hand_Middle_Finger_Proximal: [0.79849]
  left_hand_Pinky: [0.98175]
  left_hand_Ring_Finger: [0.98175]
  left_hand_Thumb_Flexion: [0.9704]
  left_hand_Thumb_Opposition: [0]

