[left_hand_q, left_hand_r]:
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.0650583123580087]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.8860448836502619]
      left_hand_Ring_Finger: [0.9684691620304948]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.1778738638154464]
    Optional:
      distance: 0.02531415768441236
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.03380401568692178]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.8482550321574672]
      left_hand_Ring_Finger: [0.9751700764765847]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.6620361418610439]
    Optional:
      distance: 0.0253821953917171
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.06074610176724381]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.8498546682434972]
      left_hand_Ring_Finger: [0.9553286079466925]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.4471556328096427]
    Optional:
      distance: 0.02566182389322341

[left_hand_q, left_hand_t]:
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.0132597322417656]
      left_hand_Index_Finger_Distal: [1.332351406952366]
      left_hand_Index_Finger_Proximal: [0.7111250591758639]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.6349518102768925]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.8684666132466635]
    Optional:
      distance: 0.0281912439549561
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.1331277167342836]
      left_hand_Index_Finger_Distal: [1.26443599225441]
      left_hand_Index_Finger_Proximal: [0.7083816294756695]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.6600733792050741]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.94793756121865]
    Optional:
      distance: 0.02853838715890487
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.05698382548133377]
      left_hand_Index_Finger_Distal: [1.236882738930639]
      left_hand_Index_Finger_Proximal: [0.7969948976128433]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.6082534183805692]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.8626129007457057]
    Optional:
      distance: 0.03090546127552286

[left_hand_s, left_hand_t]:
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.003017523781768977]
      left_hand_Index_Finger_Distal: [0.6015784053220414]
      left_hand_Index_Finger_Proximal: [0.4356765290383366]
      left_hand_Middle_Finger_Distal: [1.13390382169839]
      left_hand_Middle_Finger_Proximal: [0.1929556030138466]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.8572379452510737]
    Optional:
      distance: 0.02516629999656994
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.008173713633860461]
      left_hand_Index_Finger_Distal: [0.3279323298586533]
      left_hand_Index_Finger_Proximal: [0.4676977809161391]
      left_hand_Middle_Finger_Distal: [0.8887834286703729]
      left_hand_Middle_Finger_Proximal: [0.2366051538215135]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.1296348505884642]
    Optional:
      distance: 0.02528882306550538
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.00766672153933905]
      left_hand_Index_Finger_Distal: [0.3831719685457647]
      left_hand_Index_Finger_Proximal: [0.649519147524424]
      left_hand_Middle_Finger_Distal: [1.002737901585642]
      left_hand_Middle_Finger_Proximal: [0.3727900576036866]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.1740600234790239]
    Optional:
      distance: 0.02528924598491456

