[left_hand_q, left_hand_r]:
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.01794983984786086]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.8261549403797254]
      left_hand_Ring_Finger: [0.9704154826251324]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.4185176113090245]
    Optional:
      distance: 0.02556674850990205
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.01487646201350726]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.910232574923546]
      left_hand_Ring_Finger: [0.9264868214145535]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.5912275914198021]
    Optional:
      distance: 0.0256649333146136
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.08233577173249795]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.974671636720479]
      left_hand_Ring_Finger: [0.9781472421919462]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.8295266173485434]
    Optional:
      distance: 0.02572741987368331

[left_hand_q, left_hand_t]:
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.0009765531739220022]
      left_hand_Index_Finger_Distal: [1.056035252853297]
      left_hand_Index_Finger_Proximal: [0.6523882777975291]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.6136839144236874]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9757045263707405]
    Optional:
      distance: 0.02660783329025886
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.09298448010468856]
      left_hand_Index_Finger_Distal: [1.241643483255059]
      left_hand_Index_Finger_Proximal: [0.7408555300970283]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.6841795208336553]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9370081291465089]
    Optional:
      distance: 0.0271238759813187
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.02138771848138422]
      left_hand_Index_Finger_Distal: [1.293630369721912]
      left_hand_Index_Finger_Proximal: [0.5205938014371297]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.5788020228588721]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9808520326618105]
    Optional:
      distance: 0.02719681901165662

[left_hand_s, left_hand_t]:
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.001167006172193214]
      left_hand_Index_Finger_Distal: [0.7387558442056179]
      left_hand_Index_Finger_Proximal: [0.1710279630954284]
      left_hand_Middle_Finger_Distal: [1.038882892832626]
      left_hand_Middle_Finger_Proximal: [0.07661113323529251]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.8648501446424983]
    Optional:
      distance: 0.02534298276223784
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.01431279844301753]
      left_hand_Index_Finger_Distal: [0.7625308521520346]
      left_hand_Index_Finger_Proximal: [0.706586869822077]
      left_hand_Middle_Finger_Distal: [1.240755564851686]
      left_hand_Middle_Finger_Proximal: [0.5208170364006166]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.4612917747471482]
    Optional:
      distance: 0.02535786646992381
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.001983040356868878]
      left_hand_Index_Finger_Distal: [0.1569752401271835]
      left_hand_Index_Finger_Proximal: [0.3720805379696819]
      left_hand_Middle_Finger_Distal: [0.5905003737430089]
      left_hand_Middle_Finger_Proximal: [0.1714001336593227]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.4912511047328822]
    Optional:
      distance: 0.02561288894072053

