[left_hand_q, left_hand_r]:
  JointsInvolved: [true, false, false, false, false, true, true, false, true]
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.0165867584656924]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.9307778138425201]
      left_hand_Ring_Finger: [0.9758326772830915]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9301531407447997]
    Optional:
      distance: 0.02474822640692028
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.01989633189286105]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.9222401833949844]
      left_hand_Ring_Finger: [0.9687025736702489]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.3250383005096577]
    Optional:
      distance: 0.02484774122207529
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.004055150819127448]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.8676080602282891]
      left_hand_Ring_Finger: [0.9401391150395503]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.8198519612375647]
    Optional:
      distance: 0.02489618344122618

[left_hand_q, left_hand_t]:
  JointsInvolved: [true, true, true, false, false, true, false, false, true]
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.1300551914740121]
      left_hand_Index_Finger_Distal: [1.141764607158489]
      left_hand_Index_Finger_Proximal: [0.7612230414167769]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.6714090888609644]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9850176184491254]
    Optional:
      distance: 0.02669960904834531
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.2194525981809245]
      left_hand_Index_Finger_Distal: [1.318378551589325]
      left_hand_Index_Finger_Proximal: [0.6317058918653266]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.650830709741218]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9877968974167015]
    Optional:
      distance: 0.03111323356807977
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.075205726306024]
      left_hand_Index_Finger_Distal: [0.7318523080949672]
      left_hand_Index_Finger_Proximal: [0.7552027613507235]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.5928632903613034]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9352881129160523]
    Optional:
      distance: 0.03235098239106093

[left_hand_s, left_hand_t]:
  JointsInvolved: [true, true, true, true, true, false, false, false, true]
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.02587098662077915]
      left_hand_Index_Finger_Distal: [1.063430014366284]
      left_hand_Index_Finger_Proximal: [0.666688759754994]
      left_hand_Middle_Finger_Distal: [1.300564035205171]
      left_hand_Middle_Finger_Proximal: [0.519253004745671]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.5230840134104714]
    Optional:
      distance: 0.0255125176016396
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.003172930719447322]
      left_hand_Index_Finger_Distal: [1.09182623010641]
      left_hand_Index_Finger_Proximal: [0.7446294406474452]
      left_hand_Middle_Finger_Distal: [1.217723852456547]
      left_hand_Middle_Finger_Proximal: [0.7080619568220433]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.3878538738181349]
    Optional:
      distance: 0.02557164998316365
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.02913041113014333]
      left_hand_Index_Finger_Distal: [0.9827796712554991]
      left_hand_Index_Finger_Proximal: [0.5311927085947781]
      left_hand_Middle_Finger_Distal: [1.316612920348533]
      left_hand_Middle_Finger_Proximal: [0.3373818465617951]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.389197534774756]
    Optional:
      distance: 0.02574478600111279

