[left_hand_q, left_hand_r]:
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.03187279940256849]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.8822319922550814]
      left_hand_Ring_Finger: [0.9641707379613071]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.7993628845811589]
    Optional:
      distance: 0.02496674008611661
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.02868826840978581]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.9310718958084472]
      left_hand_Ring_Finger: [0.9704261212645797]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.2082900259308983]
    Optional:
      distance: 0.02496838601551574
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.03548319725662004]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.8580060723286006]
      left_hand_Ring_Finger: [0.9791191718065529]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.7325818578383653]
    Optional:
      distance: 0.02525437659330015

[left_hand_q, left_hand_t]:
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.002678326056757942]
      left_hand_Index_Finger_Distal: [1.166449943325948]
      left_hand_Index_Finger_Proximal: [0.7260555069468124]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.7632673898088397]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9406267939185491]
    Optional:
      distance: 0.02723980801514516
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.120000805545738]
      left_hand_Index_Finger_Distal: [1.021859960372094]
      left_hand_Index_Finger_Proximal: [0.7670340309194569]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.7034759964737459]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9627768189060968]
    Optional:
      distance: 0.02873451969683431
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.03532832490813453]
      left_hand_Index_Finger_Distal: [1.205358390192501]
      left_hand_Index_Finger_Proximal: [0.4860856566640269]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.6198179477027734]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9757082758190576]
    Optional:
      distance: 0.03012546418561392

[left_hand_s, left_hand_t]:
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.00819698081756942]
      left_hand_Index_Finger_Distal: [0.8369364570402541]
      left_hand_Index_Finger_Proximal: [0.3924942646436952]
      left_hand_Middle_Finger_Distal: [1.216329120454844]
      left_hand_Middle_Finger_Proximal: [0.2576574347432167]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.01571132172464859]
    Optional:
      distance: 0.02532780318389213
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.01241560396319255]
      left_hand_Index_Finger_Distal: [0.5532987097888254]
      left_hand_Index_Finger_Proximal: [0.4781187403871655]
      left_hand_Middle_Finger_Distal: [1.022887331445236]
      left_hand_Middle_Finger_Proximal: [0.2890673141466431]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.1164954847997055]
    Optional:
      distance: 0.02536029563504289
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.02056204418374691]
      left_hand_Index_Finger_Distal: [0.6506450081337244]
      left_hand_Index_Finger_Proximal: [0.6596320875508571]
      left_hand_Middle_Finger_Distal: [1.059103243269026]
      left_hand_Middle_Finger_Proximal: [0.4515430601779791]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.4000362309336662]
    Optional:
      distance: 0.02557411557954386

