[left_hand_q, left_hand_r]:
  JointsInvolved: [true, false, false, false, false, true, true, false, true]
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.008648178846412337]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.8727059905553469]
      left_hand_Ring_Finger: [0.9700665614466998]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.2444896109845955]
    Optional:
      distance: 0.02470325318588121
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.03111439200569876]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.9240093467103434]
      left_hand_Ring_Finger: [0.9801624275303912]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.8321193699453492]
    Optional:
      distance: 0.02476870035882548
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.00690339752335567]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.9332469791526091]
      left_hand_Ring_Finger: [0.9554135115675163]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.5540601914336672]
    Optional:
      distance: 0.02517255054272896

[left_hand_q, left_hand_t]:
  JointsInvolved: [true, true, true, false, false, true, false, false, true]
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.1757649262221297]
      left_hand_Index_Finger_Distal: [1.227393268389162]
      left_hand_Index_Finger_Proximal: [0.7940629867706355]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.7488235891350196]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9697351189732785]
    Optional:
      distance: 0.02693427421990769
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.01297380601088516]
      left_hand_Index_Finger_Distal: [0.8958225002130494]
      left_hand_Index_Finger_Proximal: [0.6890250273931423]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.606842085435579]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9682120011075167]
    Optional:
      distance: 0.0285038647205903
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.02887457810430787]
      left_hand_Index_Finger_Distal: [1.304898547909688]
      left_hand_Index_Finger_Proximal: [0.5970705833844701]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.7919276325830142]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9617033015489811]
    Optional:
      distance: 0.03081909878830562

[left_hand_s, left_hand_t]:
  JointsInvolved: [true, true, true, true, true, false, false, false, true]
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.001452038842462934]
      left_hand_Index_Finger_Distal: [0.4846514095971361]
      left_hand_Index_Finger_Proximal: [0.7113124873069814]
      left_hand_Middle_Finger_Distal: [1.115977428917307]
      left_hand_Middle_Finger_Proximal: [0.499837005895474]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.181143187006563]
    Optional:
      distance: 0.02527050847698825
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.01037712362625171]
      left_hand_Index_Finger_Distal: [0.9569328253334388]
      left_hand_Index_Finger_Proximal: [0.7546488367186603]
      left_hand_Middle_Finger_Distal: [1.201965897069313]
      left_hand_Middle_Finger_Proximal: [0.6031479048871482]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.5172195694046561]
    Optional:
      distance: 0.02529447392330546
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.0135882353328634]
      left_hand_Index_Finger_Distal: [0.1950029449127615]
      left_hand_Index_Finger_Proximal: [0.4125524902658118]
      left_hand_Middle_Finger_Distal: [0.9312154144258239]
      left_hand_Middle_Finger_Proximal: [0.1102476869092486]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.5782331602900754]
    Optional:
      distance: 0.02546853454307351

