[left_hand_q, left_hand_r]:
  JointsInvolved: [true, false, false, false, false, true, true, false, true]
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.0007664016699884086]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.9277916139011504]
      left_hand_Ring_Finger: [0.9595976163218147]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.4009087370566092]
    Optional:
      distance: 0.02493408907309044
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.0006283280981238931]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.8312387493998394]
      left_hand_Ring_Finger: [0.9664987224319485]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.6870887129835784]
    Optional:
      distance: 0.0251518601312652
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.02964224234938156]
      left_hand_Index_Finger_Distal: [0]
      left_hand_Index_Finger_Proximal: [0]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.9778124187765643]
      left_hand_Ring_Finger: [0.9764867202274036]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.4106909543304937]
    Optional:
      distance: 0.02551524607267679

[left_hand_q, left_hand_t]:
  JointsInvolved: [true, true, true, false, false, true, false, false, true]
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.06338560340262483]
      left_hand_Index_Finger_Distal: [1.084693528133444]
      left_hand_Index_Finger_Proximal: [0.7186944121557451]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.679200733119389]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9854140099595999]
    Optional:
      distance: 0.02647407863027778
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.0004407445640070364]
      left_hand_Index_Finger_Distal: [1.225560915519949]
      left_hand_Index_Finger_Proximal: [0.7611184973646864]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.7190290864049457]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.8492366308228578]
    Optional:
      distance: 0.02817010890125434
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.009671001196769067]
      left_hand_Index_Finger_Distal: [0.8914875598177314]
      left_hand_Index_Finger_Proximal: [0.7648771515273676]
      left_hand_Middle_Finger_Distal: [0]
      left_hand_Middle_Finger_Proximal: [0]
      left_hand_Pinky: [0.6769837434745277]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9209684771043481]
    Optional:
      distance: 0.02898014028733462

[left_hand_s, left_hand_t]:
  JointsInvolved: [true, true, true, true, true, false, false, false, true]
  ActionState_1:
    JointStates:
      left_hand_Finger_Spread: [0.0004982291204156354]
      left_hand_Index_Finger_Distal: [0.2674768574349582]
      left_hand_Index_Finger_Proximal: [0.3593043814967759]
      left_hand_Middle_Finger_Distal: [0.7002393994075247]
      left_hand_Middle_Finger_Proximal: [0.1694926144607924]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.1265624657843728]
    Optional:
      distance: 0.02533501016440065
  ActionState_2:
    JointStates:
      left_hand_Finger_Spread: [0.001059214587695897]
      left_hand_Index_Finger_Distal: [1.161035952397157]
      left_hand_Index_Finger_Proximal: [0.3880103527588444]
      left_hand_Middle_Finger_Distal: [1.318606047065929]
      left_hand_Middle_Finger_Proximal: [0.2395565645143273]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.1527857560837408]
    Optional:
      distance: 0.02534029551244056
  ActionState_3:
    JointStates:
      left_hand_Finger_Spread: [0.006558477834658697]
      left_hand_Index_Finger_Distal: [0.09195546173257754]
      left_hand_Index_Finger_Proximal: [0.6391512083790288]
      left_hand_Middle_Finger_Distal: [0.7547720353845507]
      left_hand_Middle_Finger_Proximal: [0.4222581037771865]
      left_hand_Pinky: [0]
      left_hand_Ring_Finger: [0]
      left_hand_Thumb_Flexion: [0]
      left_hand_Thumb_Opposition: [0.9678250226651318]
    Optional:
      distance: 0.02551213167596053

