casual:
  Type: 1
  FingersInvolved: []
  JointsInvolvedCount:
    LFB1__LFP1_1: 0
    LFB2__LFP2_1: 1
    LFB3__LFP3_1: 0
    SFB1__SFP1_1: 1
  JointPos:
    LFB1__LFP1_1: [0]
    LFB2__LFP2_1: [0.9894511764869094]
    LFB3__LFP3_1: [0]
    SFB1__SFP1_1: [0.8730974607169628]

