grasp:
  Type: 2
  Independent: true
  NInnerActions: 4
  InnerActionsNames: [trig, trig, trig, trig]
  FingersInvolved: [finger_1, finger_2, finger_3, thumb]
  JointsInvolvedCount:
    LFB1__LFP1_1: 1
    LFB2__LFP2_1: 1
    LFB3__LFP3_1: 1
    SFB1__SFP1_1: 1
  JointPos:
    LFB1__LFP1_1: [0.5]
    LFB2__LFP2_1: [0.5]
    LFB3__LFP3_1: [0.5]
    SFB1__SFP1_1: [0.5]

